plugins {
    id 'org.springframework.boot'
    id 'com.google.cloud.tools.jib' version '3.5.4'
}

description = 'MCP Server — Outils IA (Météo, Prêt, Annuaire)'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.ai:spring-ai-starter-mcp-server-webmvc'
    // API météo
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.opencsv:opencsv:5.9'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}

jib {
    from {
        image = 'eclipse-temurin:21-jre'
    }
    to {
        image = 'iagen/mcp-server:latest'
    }
    container {
        workingDirectory = '/app'
        ports = ['8081']
        jvmFlags = ['-XX:+UseZGC']
    }
}
